### ISSUE TITLE
How to use breezyslam with slamtec lidar

### ISSUE THREAD

**Issue by titusece** [zlite/rplidar#1]
Hi,
I would like to use the below breezyslam for my lidar device (rpilidar a1)and want to capture the location as image and directions to move around using motors.
I have connected my lidar to raspberry pi via USB and used '/dev/ttyUSB0'
https://github.com/zlite/rplidar/tree/master/BreezySLAM
The following code works 
timingtest.py
record_scans2.py
lidartest2.py
lidartest.py
How can I use BreezySLAM for my lidar device ?

**Comment by zlite** [comment]
Simon's master has now been updated to support the Slamtec RP-Lidar devices. Get the latest version here: 
https://github.com/simondlevy/BreezySLAM

**Comment by titusece** [comment]
Thanks for the quick help.
